---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(stargazer)
```

```{r}

library(neonUtilities)
library(tidyverse)
library(ggpubr)
library(vegan)
# devtools::install("admahood/neondiversity")
library(neondiversity) 
options(stringsAsFactors = FALSE)

####################
# downloading data #
####################
sites <- c("SRER", "ONAQ", "MOAB", "JORN")

# if statement helps avoid downloading over and over
if(!file.exists("data/diversity.RDS")){
  loadByProduct(dpID = "DP1.10058.001", 
                site = sites, 
                check.size = F) -> x
  saveRDS(x, "data/diversity.RDS")}else{
x<-readRDS("data/diversity.RDS")}

#######################
# using neondiversity #
#######################

plot_level <- get_diversity_info(neon_div_object = x, scale = "plot")

```

```{r, results='asis'}
for_table <- plot_level %>%
  rename(Site=site) %>%
  group_by(Site) %>%
  summarise(`Relative Cover Exotics (%)` = round(mean(rel_cover_exotic) * 100,1),
            `Exotic Species (n)` = mean(nspp_exotic)%>% round(1),
            `Native Species (n)` = mean(nspp_native)%>% round(1)) %>%
  ungroup %>%
  stargazer(header=F,title = "Average relative cover of exotic plants per plot, and number of exotic and native species per plot at each site.",summary = F, rownames = F)

```