---
title: "tables"
author: "Adam Mahood"
date: "6/26/2020"
output: pdf_document
---

```{r include=F}

# final diversity/scale figures and models
source("R/diversity_data_prep.R")
library(lme4)
library(ggpubr)
library(ggthemes)
library(car)
library(stargazer)
library(kableExtra)

# data mongering ===============================================================

uninvaded_sites <- all_scales %>% 
  mutate(year = as.numeric(year),
         uniqueid = paste0(year+1,plotID,scale,subplotID, site)) %>%
  filter(nspp_exotic == 0) %>% 
  dplyr::select(year, plotID, scale, subplotID, site,uniqueid, 
                shannon_total, nspp_total, shannon_native, nspp_native)

uniqueids <- uninvaded_sites$uniqueid

next_year<-all_scales %>% 
  mutate(year = as.numeric(year),
         uniqueid = paste0(year,plotID,scale,subplotID, site))%>%
  filter(uniqueid %in% uniqueids) %>%
  dplyr::select(uniqueid, next_shannon_total=shannon_total, 
                next_nspp_total=nspp_total, 
                next_nspp_exotic = nspp_exotic,
                next_shannon_native=shannon_native, 
                next_nspp_native = nspp_native,
                next_shannon_exotic = shannon_exotic) %>%
  mutate(invaded = ifelse(next_nspp_exotic > 0, 1, 0))

prev_year_div <- left_join(next_year, uninvaded_sites)

# binomial models ==============================================================



# this is the ggplot model, basically... not sure how to compare glm and glmer
ma0<-all_scales %>%
  mutate(invaded = ifelse(invaded=="invaded",1,0)) %>%
  glm(invaded ~ nspp_native * scale, 
              data = ., family = "binomial")


mc0<-prev_year_div%>%
  mutate(nspp_native = scale(nspp_native)) %>%
  glm(invaded ~ nspp_native*scale, 
              data = ., family = "binomial")

# count models =================================================================


mb0<-all_scales %>%
  glm(nspp_exotic ~ nspp_native * scale, 
      data = ., family = "quasipoisson")
#not sure what to think about this stuff
md0<-prev_year_div%>%
  glm(next_nspp_exotic ~ nspp_native*scale, 
      data = ., family = "quasipoisson")
```

```{r results='asis'}
# stargazer(ma0,mb0,mc0,md0, header=F, type="html", out="regression.html")
```

```{r}
aovs<- rbind(car::Anova(ma0) %>%
    as_tibble(rownames = "variable") %>%
    mutate(response = "P(Invaded)"),
  car::Anova(mc0) %>%
    as_tibble(rownames = "variable") %>%
    mutate(response = "Exotic Richness"),
  car::Anova(md0) %>%
    as_tibble(rownames = "variable") %>%
    mutate(response = "Exotic Richness: Year 2"),
  car::Anova(mb0) %>%
    as_tibble(rownames = "variable") %>%
    mutate(response = "P(Invaded): Year 2"))

index_s <- table(aovs$response) %>% 
                 as.data.frame() %>% 
                 arrange(desc(Var1))

index_ss<- index_s$Freq
names(index_ss) <- index_s$Var1

aovs1<- aovs %>% 
  mutate(variable = replace(variable, variable == "nspp_native", 
                            "Native Richness"))%>%
  mutate(variable = replace(variable, 
                            variable == "nspp_native:scale", 
                            "Native Richness X Scale"))%>%
  mutate(variable = replace(variable, 
                            variable == "scale", 
                            "Scale")) %>%
  mutate(`LR Chisq` = round(`LR Chisq`, 1),
         `P(>Chisq)` = formatC(`Pr(>Chisq)`, format = "f", digits=3) %>% 
           as.character %>%
           replace(.=="0.000", "<0.001"))%>%
  arrange(desc(response)) %>%
  mutate(order = factor(response, levels =  c("Exotic Richness","P(Invaded)",
                                              "Exotic Richness: Year 2",
                                              "P(Invaded): Year 2"))) %>%
  arrange(order)%>%
  dplyr::select(response, variable, "LR Chisq", "P(>Chisq)")
write_csv(aovs1, "aov_table.csv")
#   kable(aovs,
#       booktabs=TRUE,
#       # linesep=c("","","\\addlinespace"),
#       # escape=F,
#       # col.names=c("",
#       #             "F", "P(>F)","F",
#       #             "P(>F)","F", "P(>F)"),
#         caption = "Type II ANOVA results") %>%
# # add_header_above(c(" " = 1, "Year" = 2, "Invasion Stage" = 2, "Year x Invasion Stage"=2)) %>%
#   kableExtra::kable_styling(font_size = 8)
#   #   group_rows(index = index_ss)

```